server:
  port: 8080


zuul:
  routes:
        discount:
          path: /discount/**
          serviceId: discount
        user:
          path: /user/**
          serviceId: user
  #stripPrefix: false
  #ignoredServices: "*"


security:
  basic:
    enable: false

---

spring:
  profiles: development
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

#ribbon:
#  eureka:
#    enabled: false


