server:
  port: 8761

spring:
 fail-fast: true

eureka:
#  instance:
#    hostname: eurekaserver
#    prefer-ip-address: true
  instance:
      hostname: localhost
  client:
    serviceUrl:
            defaultZone: http://localhost:8761/
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  security:
    enabled: false

#spring:
#  profiles: development