server:
  port: 8761

spring:
 fail-fast: true

eureka:
  instance:
    hostname: eurekaserver
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  security:
    enabled: false

spring:
  profiles: development
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/

#---
#
#spring:
#  profiles: development
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#        defaultZone: http://localhost:8761/
#
#---
#
#spring:
#  profiles: docker
#eureka:
#  instance:
#    hostname: eurekaserver
#  client:
#      serviceUrl:
#          defaultZone: http://eurekaserver:8761/
#
#
