server:
  port: 8100

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  generate-ddl: true
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123qwe

---

spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5436/user

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: docker
  datasource:
      url: jdbc:postgresql://db:5436/user


#ribbon:
#  eureka:
#    enabled: false
#  context-path: /user
#security.basic.enable:false
#management.security.enabled:false
